[workspace]

members = [
    "omni-led",
    "oled-applications/audio",
    "oled-applications/clock",
    "oled-applications/media",
    "oled-applications/weather",
    "oled-api",
    "oled-derive",
    "setup",
]

resolver = "2"
