[workspace]

members = [
    "steelseries_oled",
    "oled-applications/audio",
    "oled-applications/clock",
    "oled-applications/media",
    "oled-applications/weather",
    "debug-runner",
    "setup",
]

resolver = "2"
