[package]
name = "steelseries_oled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
freetype-rs = "0.32"
libloading = "0.8"
mlua = { version = "0.8", features = ["lua54", "vendored"] }
once_cell = "1.17"
quote = "1.0"
rust_lisp = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strfmt = "0.2"
syn = "2.0"
tokio = { version = "1", features = ["full"] }
ureq = { version = "2.4", features = ["json"] }
warp = "0.3"