[config]
default_to_workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

# Tasks for creating and running the setup binary
[tasks.build-setup-dependencies]
description = "Build binaries that will be included in the setup binary"
command = "cargo"
args = ["build", "--release", "--package=omni-led", "--package=audio", "--package=clock",
    "--package=images", "--package=media", "--package=weather"]

[tasks.build-setup]
description = "Build the setup binary"
command = "cargo"
args = ["build", "--release", "--package=omni-led-setup"]
dependencies = ["build-setup-dependencies"]

[tasks.run-setup]
description = "Run setup"
command = "cargo"
args = ["run", "--release", "--bin=omni-led-setup", "--", "install", "--interactive"]
dependencies = ["build-setup"]

# Tasks for building and running locally using cargo run
[tasks.build]
description = "Build development binaries in debug mode"
command = "cargo"
args = ["build", "--features=dev", "--package=omni-led", "--package=audio", "--package=clock",
    "--package=images", "--package=media", "--package=weather"]

[tasks.build-release]
description = "Build development binaries in release mode"
command = "cargo"
args = ["build", "--release", "--features=dev", "--package=omni-led", "--package=audio",
    "--package=clock", "--package=images", "--package=media", "--package=weather"]

[tasks.run]
description = "Run development binaries in debug mode"
command = "cargo"
args = ["run", "--features=dev"]
dependencies = ["build"]

[tasks.run-release]
description = "Run development binaries in release mode"
command = "cargo"
args = ["run", "--release", "--features=dev"]
dependencies = ["build-release"]

[tasks.build-test-binaries]
description = "Build test application binaries"
command = "cargo"
args = ["build", "--package=test_events"]

[tasks.test]
description = "Run tests"
command = "cargo"
args = ["test", "--package=omni-led", "--features=dev", "--no-fail-fast"]
dependencies = ["build", "build-test-binaries"]
