[package]
name = "steelseries_oled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_rs = { path = "../common/common_rs" }
freetype-rs = "0.30"
libloading = "0.7"
rust_lisp = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strfmt = "0.1"
ureq = { version = "2.4", features = ["json"] }