[package]
name = "steelseries_oled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_rs = { path = "../common/common_rs" }
libloading = "0.7"
serde_json = "1.0"
ureq = { version = "2.4", features = ["json"] }