name: 'Setup Env'

description: 'Install dependencies and checkout the code'
runs:
  using: composite
  steps:
    - name: Install Linux dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt update
        sudo apt install \
          gcc \
          g++ \
          libappindicator3-dev \
          libdbus-1-dev \
          libfontconfig-dev \
          libgtk-3-dev \
          libpulse-dev \
          libudev-dev \
          libx11-dev \
          libxdo-dev \
          pkg-config \
          protobuf-compiler
      shell: bash

    - name: Install Windows dependencies
      if: ${{ runner.os == 'Windows' }}
      run: choco install protoc -y
      shell: cmd

    - name: Install macOS dependencies
      if: ${{ runner.os == 'macOS' }}
      run: brew install protobuf
      shell: bash

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1
