[package]
name = "omni-led-derive"
version = "0.11.4"
authors = ["Michał Bałabanow <m.balabanow@gmail.com>"]
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
omni-led-derive-impl = { path = "omni-led-derive-impl" }

[dev-dependencies]
mlua = { version = "0.12", features = ["lua54", "vendored", "macros"] }
regex = "1.10"

[features]
default-impl = ["omni-led-derive-impl/default-impl"]
from-lua-value = ["omni-led-derive-impl/from-lua-value"]
lua-enum = ["omni-led-derive-impl/lua-enum"]
lua-name = ["omni-led-derive-impl/lua-name"]
lua-settings = ["omni-led-derive-impl/lua-settings"]
plugin-entry = ["omni-led-derive-impl/plugin-entry"]
