[package]
name = "test_events"
version = "0.4.1"
authors = ["Michał Bałabanow <m.balabanow@gmail.com>"]
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
omni-led-api = { path = "../../omni-led-api" }
tokio = { version = "1.38", features = ["full"] }
